"""
Django settings for busy_project project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os

# ---------------------------------------------
# BASE CONFIGURATION
# ---------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-wr9kx4-a&)08q0#8=sw#_8+2*+op9s@f84moo-or(!-lajad)('
DEBUG = True
ALLOWED_HOSTS = []

# ---------------------------------------------
# APPLICATIONS
# ---------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'items',  # ✅ your custom app
]

# ---------------------------------------------
# MIDDLEWARE
# ---------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------------------------
# URL / TEMPLATES / WSGI
# ---------------------------------------------
ROOT_URLCONF = 'busy_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ✅ This allows you to also keep global templates
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'busy_project.wsgi.application'

# ---------------------------------------------
# DATABASE CONFIG
# ---------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # ✅ Indian time zone (you can keep UTC if you prefer)
USE_I18N = True
USE_TZ = True

# ---------------------------------------------
# STATIC & MEDIA FILE CONFIG
# ---------------------------------------------
# URL to access static files
STATIC_URL = '/static/'

# Where Django looks for additional static files during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'items', 'static'),  # ✅ Points to /items/static/
]

# Where static files are collected for deployment
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# (Optional) Media setup if you ever add file uploads later
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ---------------------------------------------
# DEFAULT FIELD TYPE
# ---------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
