# Generated by Django 5.2.4 on 2025-11-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_bill_customer_address_bill_customer_phone_and_more'),
    ]

    operations = [
    ]
