# Generated by Django 5.2.4 on 2025-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_estimateitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='billitem',
            options={'ordering': ['id'], 'verbose_name': 'Bill Item', 'verbose_name_plural': 'Bill Items'},
        ),
        migrations.AlterModelOptions(
            name='estimatebill',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ['id'], 'verbose_name': 'Estimate Item', 'verbose_name_plural': 'Estimate Items'},
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
