# Generated by Django 5.2.4 on 2025-11-06 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
